### ISSUE TITLE
closing browser crashes application

### ISSUE THREAD

**Issue by ispysoftware** [radioman/WebRtc.NET#31]
When closing the web browser (chrome 57.0.2987.21 beta) The app crashes with 

An unhandled exception of type 'System.AccessViolationException' occurred in WebRtc.NET.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

- this is a clean build from github running on windows 10.

   at WebRtc.NET.ManagedConductor.!ManagedConductor() in d:\projects\ispy\ispyuniversal\webrtc.net\webrtc.net\src\managed.cpp:line 327
   at WebRtc.NET.ManagedConductor.~ManagedConductor() in d:\projects\ispy\ispyuniversal\webrtc.net\webrtc.net\src\managed.cpp:line 196
   at WebRtc.NET.ManagedConductor.Dispose(Boolean A_0) in d:\projects\ispy\ispyuniversal\webrtc.net\webrtc.net\include\webrtc\media\base\yuvframegenerator.h:line 0
   at WebRtc.NET.ManagedConductor.Dispose()
   at WebRtc.NET.Demo.WebRTCServer.<>c__DisplayClass19_1.<OnReceive>b__0() in D:\Projects\iSpy\iSpyUniversal\WebRtc.NET\WebRtc.NET.Demo\WebRTCServer.cs:line 227
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by ispysoftware** [comment]
Looking into it, I don't think the data channel is closing when the connection is closing

**Comment by ispysoftware** [comment]
I think it's something to do with YuvFrameGenerator

**Comment by radioman** [comment]
what if you use internal capturer by unchecking virtualcam?

**Comment by radioman** [comment]
thanks for the hint, fixed
