### ISSUE TITLE
Crash on Disposing  

### ISSUE THREAD

**Issue by EbramSamy** [radioman/WebRtc.NET#54]
I get this issue:
at WebRtc.NET.WebRtcNative.DeleteConductor(IntPtr p)
   at WebRtc.NET.WebRtcNative.Dispose()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I was capturing the screen using the native module to capture the screen. I stopped capturing and on disposing webrtcNative object I got this Issue.

**Comment by Kevin-Herrera** [comment]
Im seeing the same thing. @EbramSamy did you end up finding a fix?

**Comment by dsp85103** [comment]
Im also seeing the same thing ..... The Native::Conductor crash on delete ... @EbramTawfik  did you end up finding a fix ?

**Comment by EbramTawfik** [comment]
Do you use master branch or staging branch?

**Comment by dsp85103** [comment]
@EbramTawfik  thank you for ur reply.
I using staging branch. I try WebrtcNative's dispose method (it call DeleteConductor) in Webrtc.Net.Demo, it work. 
But it not working in my case. It seems like crash on "delete conductor". I dont know how to debug this.  Because I compiled that to dll and use it in my case (C#). BTW do you have any idea for debug this :D ?

**Comment by Riton2013** [comment]
> @EbramTawfik thank you for ur reply. I using staging branch. I try WebrtcNative's dispose method (it call DeleteConductor) in Webrtc.Net.Demo, it work. But it not working in my case. It seems like crash on "delete conductor". I dont know how to debug this. Because I compiled that to dll and use it in my case (C#). BTW do you have any idea for debug this :D ?

I have same problem, do you know how to fixed this?
